export type EmployeeStatus = 'Active' | 'Probation' | 'Inactive';
export type EmploymentType = 'Full-time' | 'Contract';
export type Gender = 'Male' | 'Female';
export type DocumentType = 'Visa' | 'Emirates ID' | 'Passport' | 'Labour Card' | 'Other';
export type ActivityType = 'joined' | 'documents' | 'probation' | 'salary';

export interface EmployeeDocument {
  type: DocumentType;
  number: string;
  /** ISO date, e.g. 2026-10-16. */
  expiryDate: string;
  fileName: string | null;
}

export interface ActivityEvent {
  type: ActivityType;
  title: string;
  description: string;
  /** ISO date. */
  date: string;
}

export interface Employee {
  /** json-server record id, used in routes. */
  id: number;
  /** Display id, e.g. E-1001. */
  employeeId: string;

  // Personal
  firstName: string;
  lastName: string;
  email: string;
  /** Dial code, e.g. +971. */
  countryCode: string;
  /** National number without the dial code, e.g. 502147789. */
  mobile: string;
  /** ISO date. */
  dateOfBirth: string;
  gender: Gender;
  nationality: string;
  photoUrl: string | null;

  // Job
  department: string;
  designation: string;
  /** ISO date. */
  joiningDate: string;
  employmentType: EmploymentType;
  /** ISO date; null unless employmentType is Contract. */
  contractEndDate: string | null;
  /** 24-hour HH:mm. */
  shiftStart: string;
  /** 24-hour HH:mm. */
  shiftEnd: string;
  skills: string[];
  /** Monthly salary in AED. */
  salary: number;

  // Other
  documents: EmployeeDocument[];
  status: EmployeeStatus;
  notes: string;
  activity: ActivityEvent[];

  /** ISO timestamps, maintained by EmployeeService. */
  createdAt: string;
  updatedAt: string;
}

export type EmployeePayload = Omit<Employee, 'id' | 'createdAt' | 'updatedAt'>;

/** A new employee's display id is generated by EmployeeService.addEmployee(). */
export type NewEmployeePayload = Omit<EmployeePayload, 'employeeId'>;

export function fullName(employee: Pick<Employee, 'firstName' | 'lastName'>): string {
  return `${employee.firstName} ${employee.lastName}`.trim();
}
