name: Deploy Angular to GitHub Pages

on:
  push:
    branches:
      - master # Triggers on push to the master branch

permissions:
  contents: write # Needed for the action to push to the gh-pages branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Build Angular Project
        run: npm run build -- --base-href /infithra_ems/

      - name: Handle SPA Routing (404 Fallback)
        run: cp dist/infithra_ems/browser/index.html dist/infithra_ems/browser/404.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/infithra_ems/browser
